
import './globals.css'
import { ThemeProvider } from '@/provider/ThemeProvider'
import {
   Lato
} from "next/font/google"

const lato = Lato({
  weight: ["300", "400", "700"], 
  style:["italic", "normal"], 
  subsets: ["latin"]

})

export const metadata = {
  title: 'CV | Eduardo Martínez',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className='h-full'>
      <body className={lato.className}>
        <ThemeProvider attribute="class" defaultTheme ="system" enableSystem >
          <div className='flex flex-col h-full'>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
